# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import payment_pb2 as payment__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in payment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePayment = channel.unary_unary(
                '/payment.PaymentService/CreatePayment',
                request_serializer=payment__pb2.CreatePaymentRequest.SerializeToString,
                response_deserializer=payment__pb2.CreatePaymentResponse.FromString,
                _registered_method=True)
        self.VerifyCallback = channel.unary_unary(
                '/payment.PaymentService/VerifyCallback',
                request_serializer=payment__pb2.VerifyCallbackRequest.SerializeToString,
                response_deserializer=payment__pb2.VerifyCallbackResponse.FromString,
                _registered_method=True)
        self.QueryTransaction = channel.unary_unary(
                '/payment.PaymentService/QueryTransaction',
                request_serializer=payment__pb2.QueryTransactionRequest.SerializeToString,
                response_deserializer=payment__pb2.QueryTransactionResponse.FromString,
                _registered_method=True)


class PaymentServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreatePayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyCallback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePayment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePayment,
                    request_deserializer=payment__pb2.CreatePaymentRequest.FromString,
                    response_serializer=payment__pb2.CreatePaymentResponse.SerializeToString,
            ),
            'VerifyCallback': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyCallback,
                    request_deserializer=payment__pb2.VerifyCallbackRequest.FromString,
                    response_serializer=payment__pb2.VerifyCallbackResponse.SerializeToString,
            ),
            'QueryTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryTransaction,
                    request_deserializer=payment__pb2.QueryTransactionRequest.FromString,
                    response_serializer=payment__pb2.QueryTransactionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment.PaymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payment.PaymentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/CreatePayment',
            payment__pb2.CreatePaymentRequest.SerializeToString,
            payment__pb2.CreatePaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyCallback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/VerifyCallback',
            payment__pb2.VerifyCallbackRequest.SerializeToString,
            payment__pb2.VerifyCallbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.PaymentService/QueryTransaction',
            payment__pb2.QueryTransactionRequest.SerializeToString,
            payment__pb2.QueryTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
