# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x07payment\"\x88\x01\n\x14\x43reatePaymentRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x03\x12\x12\n\norder_info\x18\x03 \x01(\t\x12\x12\n\nreturn_url\x18\x04 \x01(\t\x12\x12\n\nip_address\x18\x05 \x01(\t\x12\x12\n\norder_type\x18\x06 \x01(\t\"T\n\x15\x43reatePaymentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bpayment_url\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\"\x92\x01\n\x15VerifyCallbackRequest\x12\x45\n\x0cvnpay_params\x18\x01 \x03(\x0b\x32/.payment.VerifyCallbackRequest.VnpayParamsEntry\x1a\x32\n\x10VnpayParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa2\x01\n\x16VerifyCallbackResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x12\n\nis_success\x18\x02 \x01(\x08\x12\x16\n\x0etransaction_no\x18\x03 \x01(\t\x12\x10\n\x08order_id\x18\x04 \x01(\t\x12\x0e\n\x06\x61mount\x18\x05 \x01(\x03\x12\x15\n\rresponse_code\x18\x06 \x01(\t\x12\x11\n\tbank_code\x18\x07 \x01(\t\"T\n\x17QueryTransactionRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63reate_date\x18\x02 \x01(\t\x12\x12\n\nip_address\x18\x03 \x01(\t\"\x97\x01\n\x18QueryTransactionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0etransaction_no\x18\x02 \x01(\t\x12\x18\n\x10transaction_type\x18\x03 \x01(\t\x12\x10\n\x08pay_date\x18\x04 \x01(\t\x12\x15\n\rresponse_code\x18\x05 \x01(\t\x12\x0f\n\x07message\x18\x06 \x01(\t2\x8c\x02\n\x0ePaymentService\x12N\n\rCreatePayment\x12\x1d.payment.CreatePaymentRequest\x1a\x1e.payment.CreatePaymentResponse\x12Q\n\x0eVerifyCallback\x12\x1e.payment.VerifyCallbackRequest\x1a\x1f.payment.VerifyCallbackResponse\x12W\n\x10QueryTransaction\x12 .payment.QueryTransactionRequest\x1a!.payment.QueryTransactionResponseB\x1b\n\x17\x63om.venue.payment.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.venue.payment.protoP\001'
  _globals['_VERIFYCALLBACKREQUEST_VNPAYPARAMSENTRY']._loaded_options = None
  _globals['_VERIFYCALLBACKREQUEST_VNPAYPARAMSENTRY']._serialized_options = b'8\001'
  _globals['_CREATEPAYMENTREQUEST']._serialized_start=27
  _globals['_CREATEPAYMENTREQUEST']._serialized_end=163
  _globals['_CREATEPAYMENTRESPONSE']._serialized_start=165
  _globals['_CREATEPAYMENTRESPONSE']._serialized_end=249
  _globals['_VERIFYCALLBACKREQUEST']._serialized_start=252
  _globals['_VERIFYCALLBACKREQUEST']._serialized_end=398
  _globals['_VERIFYCALLBACKREQUEST_VNPAYPARAMSENTRY']._serialized_start=348
  _globals['_VERIFYCALLBACKREQUEST_VNPAYPARAMSENTRY']._serialized_end=398
  _globals['_VERIFYCALLBACKRESPONSE']._serialized_start=401
  _globals['_VERIFYCALLBACKRESPONSE']._serialized_end=563
  _globals['_QUERYTRANSACTIONREQUEST']._serialized_start=565
  _globals['_QUERYTRANSACTIONREQUEST']._serialized_end=649
  _globals['_QUERYTRANSACTIONRESPONSE']._serialized_start=652
  _globals['_QUERYTRANSACTIONRESPONSE']._serialized_end=803
  _globals['_PAYMENTSERVICE']._serialized_start=806
  _globals['_PAYMENTSERVICE']._serialized_end=1074
# @@protoc_insertion_point(module_scope)
